@echo off
REM Generated by vbox_installer.py - review before running
VBoxManage createmedium disk --filename "A:\KNO\disks\KNO_AI_OS.vdi" --size 20480 --format VDI
VBoxManage storagectl "KNO_AI_OS" --name "SATA" --add sata --controller IntelAhci
VBoxManage storageattach "KNO_AI_OS" --storagectl "SATA" --port 0 --device 0 --type hdd --medium "A:\KNO\disks\KNO_AI_OS.vdi"
VBoxManage modifyvm "KNO_AI_OS" --nic1 bridged
VBoxManage modifyvm "KNO_AI_OS" --audio none
