"""
VBox Installer Helper
---------------------
Generates a Windows .cmd file with VBoxManage commands to:
- create a virtual disk image (VDI)
- attach it to an existing VM's SATA controller (creates controller if needed)
- configure network adapter (nat / bridged / hostonly)
- optionally disable/enable audio (user-reviewed)

Usage:
    python vbox_installer.py --vm-name MyVM --disk-path ./disks/MyVM.vdi --disk-size 10240 --network nat

Options:
    --execute    : actually run the generated commands (requires VBoxManage in PATH and admin rights when needed)
    --bridge-adapter "Intel(R) ..." : adapter name for bridged mode

Note: This script generates commands for review by default. It does not assume which audio host driver to use; it includes a safe "--audio none" option and leaves enabling audio as an explicit choice.

Author: Generated by assistant
"""

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path

CMD_TEMPLATE = []


def which_vboxmanage():
    # On Windows, VBoxManage.exe should be on PATH if VirtualBox is installed
    return shutil.which('VBoxManage') or shutil.which('VBoxManage.exe')


def build_commands(vm_name: str, disk_path: str, disk_size_mb: int, network: str, bridge_adapter: str | None, audio_enable: bool):
    commands = []
    disk_abs = str(Path(disk_path).expanduser().resolve())

    # Create disk (VDI)
    commands.append(f'VBoxManage createmedium disk --filename "{disk_abs}" --size {int(disk_size_mb)} --format VDI')

    # Add SATA controller (idempotent - may error if already exists)
    # Use try/except when executing; keep commands explicit for review
    commands.append(f'VBoxManage storagectl "{vm_name}" --name "SATA" --add sata --controller IntelAhci')

    # Attach disk to controller port 0
    commands.append(f'VBoxManage storageattach "{vm_name}" --storagectl "SATA" --port 0 --device 0 --type hdd --medium "{disk_abs}"')

    # Network configuration
    net = network.lower() if network else 'nat'
    if net == 'nat':
        commands.append(f'VBoxManage modifyvm "{vm_name}" --nic1 nat')
    elif net == 'bridged':
        commands.append(f'VBoxManage modifyvm "{vm_name}" --nic1 bridged')
        if bridge_adapter:
            commands.append(f'VBoxManage modifyvm "{vm_name}" --bridgeadapter1 "{bridge_adapter}"')
    elif net == 'hostonly':
        commands.append(f'VBoxManage modifyvm "{vm_name}" --nic1 hostonly')
    else:
        # allow custom raw options
        commands.append(f'Verify network option: "{network}"')

    # Audio configuration (safe default: none)
    if audio_enable:
        # Enabling audio driver selection is environment-specific; leave as a placeholder
        commands.append(f'REVIEW: To enable audio, run: VBoxManage modifyvm "{vm_name}" --audio <host-driver>')
    else:
        commands.append(f'VBoxManage modifyvm "{vm_name}" --audio none')

    return commands


def write_cmd_file(commands, output_path: str):
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write('@echo off\n')
        f.write('REM Generated by vbox_installer.py - review before running\n')
        for cmd in commands:
            # If a command starts with REVIEW:, write as echo comment
            if cmd.startswith('REVIEW:'):
                f.write(f'echo {cmd[7:]}\n')
            else:
                f.write(cmd + '\n')
    return str(path)


def run_commands(commands):
    vbox = which_vboxmanage()
    if not vbox:
        raise RuntimeError('VBoxManage not found in PATH. Install VirtualBox or add VBoxManage to PATH.')

    results = []
    for cmd in commands:
        if cmd.startswith('REVIEW:'):
            results.append({'cmd': cmd, 'skipped': True, 'note': 'REVIEW'})
            continue
        # Execute via subprocess; using shell=True for Windows command strings
        try:
            proc = subprocess.run(cmd, shell=True, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            results.append({'cmd': cmd, 'returncode': proc.returncode, 'stdout': proc.stdout, 'stderr': proc.stderr})
        except subprocess.CalledProcessError as e:
            results.append({'cmd': cmd, 'returncode': e.returncode, 'stdout': e.stdout, 'stderr': e.stderr})
            # stop on failure
            break
    return results


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Prepare VirtualBox VDI and VM settings (Windows-friendly).')
    parser.add_argument('--vm-name', required=True, help='Target VM name to attach disk and configure')
    parser.add_argument('--disk-path', default='./disks/{vm}.vdi', help='Path to VDI file (use {vm} to substitute VM name)')
    parser.add_argument('--disk-size', type=int, default=10240, help='Disk size in MB (default 10240 = 10GB)')
    parser.add_argument('--network', choices=['nat','bridged','hostonly'], default='nat', help='Network mode')
    parser.add_argument('--bridge-adapter', default=None, help='Host network adapter name for bridged mode')
    parser.add_argument('--audio', action='store_true', help='Enable audio (script will add a REVIEW comment; pick host driver manually)')
    parser.add_argument('--execute', action='store_true', help='Execute the generated VBoxManage commands (runs them now)')
    parser.add_argument('--out-cmd', default='./vbox_commands_{vm}.cmd', help='Output .cmd filename template')

    args = parser.parse_args()

    vm = args.vm_name
    disk_path = args.disk_path.format(vm=vm)
    out_cmd = args.out_cmd.format(vm=vm)

    commands = build_commands(vm, disk_path, args.disk_size, args.network, args.bridge_adapter, args.audio)

    cmd_file = write_cmd_file(commands, out_cmd)
    print(f'Wrote command file: {cmd_file}')

    print('\nCommands to review:')
    for c in commands:
        print('  ' + c)

    if args.execute:
        confirm = input('Execute these commands now? (yes/NO): ').strip().lower()
        if confirm in ('yes','y'):
            print('Running commands...')
            res = run_commands(commands)
            print('\nExecution results:')
            print(json.dumps(res, indent=2))
        else:
            print('Execution cancelled by user.')

